name: Python CI
'on':
  push:
    branches:
      - '**'
jobs:
  run-ci:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
          cache-dependency-path: poetry.lock
      - name: Set Poetry environment
        run: |
          poetry env use 3.10
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Install Tesseract
        run: |
          if [ ! -d "/usr/local/Cellar/tesseract" ]; then
            brew install tesseract
          fi
      - name: Run tests
        run: poetry run pytest
      - name: Check formatting with Black
        uses: psf/black@stable
        with:
          options: '--check --exclude "(alembic|venv)/"'
      - name: Run Flake8
        run: poetry run flake8 
