name: Python CI

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r requirements.txt


      - name: Install Python Black
        run: pip install black

      - name: Install the module in development mode
        run: pip install -e .

      - name: Run Python Black
        run: python -m black .

      - name: Run headless test
        uses: coactions/setup-xvfb@v1
        with:
          run: python -m pytest
          working-directory: ./ # Optional: Specify the working directory if needed
          options: # Optional: Add any additional options or arguments for pytest

      - name: Run Linting Check
        run: pylint --rcfile=.pylintrc .
