name: Python CI

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Python Black
        run: pip install black

      - name: Run Python Black
        run: python -m black .

      - name: Run Python Tests
        run: pytest

      - name: Run Linting Check
        run: pylint --rcfile=.pylintrc .
