name: Python CI

on:
  push:
    branches:
      - '**'

jobs:
  run-ci:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache Poetry install
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}

      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Cache Homebrew Packages
        id: cache-homebrew-packages
        uses: actions/cache@v3
        env:
          cache-name: homebrew-packages
        with:
          path: $(brew --prefix)
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ hashFiles('.config/brew/Brewfile') }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install Tesseract
        run: brew install tesseract
        if: steps.cache-homebrew-packages.outputs.cache-hit != 'true'

      - name: Run tests
        run: poetry run pytest

      - name: Check formatting with Black
        run: poetry run black --check --exclude "(alembic|venv)/" .

      - name: Run Flake8
        run: poetry run flake8
